#!/bin/bash
#NK: We need bash for the redirects below


set -e


# Execute any healtchcheck scripts
while read i
do
	if [ -e "${i}" ]; then
		. "${i}"
	fi
done < <(find /docker-healthcheck.d -type f -name '*.sh' | sort)
